### ISSUE TITLE
Problems with modifying the model

### ISSUE THREAD

**Issue by oycool** [reiniscimurs/DRL-robot-navigation#96] opened 2023-12-28 03:38 UTC
Hi Reinis Cimurs, first of all, thank you very much for sharing.
I tried modifying your model into an Ackermann car. There is no error when launching but the car still does not move. The running picture is as follows. I hope you can give me some suggestions to solve the problem. 
Looking forward to your reply.
![截图4](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/fa8d6f85-4e25-4592-beba-73f8fef5749b)
![截图5](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/3dc3f1ae-56dd-42b6-9a85-5f851310163b)

**Comment by reiniscimurs** [comment] 2023-12-28 09:23
Hi,

I see you are using ROS melodic distribution in your code. This is a version I am no longer supporting as I have no way of testing it so generally any issues arising in this distribution would be up to you to solve.


That being said, I can take a brief look if you share the code changes that you have implemented. I don't really see anything just from the log messages.

**Comment by cd310105974** [comment] 2023-12-28 13:01
Thank you for your reply.
In addition to changing your model to Ackerman, I also made a few modifications:
1. Using the 'libgazebo_ros_control.so' plugin and 'transmission' to control the car.
![kz](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/b365468e-d648-44cf-a346-b76334d6cd17)

2. Setting up the controller.
![pz](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/6c358d18-b1ab-4ba3-a38e-ecd9859fc436)

3. Calculating the speed and assign it to the controller command.
![fz1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/a1a14ed8-6337-4d31-87aa-be8c5edeffc5)
![fz2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/72ebd97c-a1ab-40f4-bc81-72cf4ce358f5)

4. Posting the odom topics and the tf.
![odom1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/b0f9ae40-167c-4ce2-8368-456bd93b0061)
![odom2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/02432654-2f21-42bc-a177-a4a73114a10c)

This is my launch file.
![launch](https://github.com/reiniscimurs/DRL-robot-navigation/assets/128568119/17f7e35f-f1c5-4d96-8d4b-6c54e045c923)

These are the modifications I made to the code.

**Comment by reiniscimurs** [comment] 2023-12-28 13:28
I just took a quick look but I suggest checking ros topics and the names for them. It seems to me you are using a namespace in the robot controller plugin that was not used in the default (or it was passed in instead of hardcoding it). So if your cmd_vel topic is in a different namesake, the publisher will not be able to send the message to the controller and the robot will not move. See the outputs from "rostopic list". Also would be good to see RQT tree and published nodes.

**Comment by cd310105974** [comment] 2023-12-29 08:41
Thank you very much for your reply.
After inspection, the car was finally ready to drive. The problem is the namespace. It is not easy for a newbie. 
However, I discovered a problem. In rviz, the laser behind the car will move. This problem also occurs with the gif you uploaded. Have you analyzed the reason?

**Comment by reiniscimurs** [comment] 2023-12-29 12:01
What do you mean by "laser behind the car"? We do not have a laser in the main repo branch at all, just the velodyne lidar,and there is no laser behind the robot in other branches. If you mean the swaying of the laser data in the gif, that is due to running the training with increased simulation speed as described in: https://medium.com/@reinis_86651/deep-reinforcement-learning-in-mobile-robot-navigation-tutorial-part5-some-extra-stuff-b744852345ac
There are some drawbacks to increasing the speed.

**Closed** 2024-04-28 13:09 UTC
Labels: change robot
